export const LOAD_TEAMMEMBERS_SUCCESS = 'LOAD_TEAMMEMBERS_SUCCESS';
export const LOAD_PROJECTCODES_SUCCESS = 'LOAD_PROJECTCODES_SUCCESS';
export const CREATE_TEAMMEMBER_SUCCESS = 'CREATE_TEAMMEMBER_SUCCESS';
export const UPDATE_TEAMMEMBER_SUCCESS = 'UPDATE_TEAMMEMBER_SUCCESS';
